#!/bin/sh

TEST_IMAGE_NAME="asciidoctor-test"
TEST_IMAGE_TAG="latest"

test_Build() {
  docker build -t "${TEST_IMAGE_NAME}:${TEST_IMAGE_TAG}" .
}

test_Executables() {
  for CMD in "blockdiag" "erd" "pandoc"; do
    OUTPUT=$(docker run ${TEST_IMAGE_NAME}:${TEST_IMAGE_TAG} ${CMD} -h)
    assertNotEquals " can't run ${PRG};" "${OUTPUT}" ""
  done
}

test_Cleanup() {
  # cleanup
  docker rmi -f ${TEST_IMAGE_NAME}:${TEST_IMAGE_TAG}
}

for DEPENDENCY in docker shunit2; do
  if [ -z $(which ${DEPENDENCY}) ]; then
    echo "Missing dependency '${DEPENDENCY}'"
    exit 1
  fi
done

. shunit2
